apiVersion: apps/v1
kind: Deployment
metadata:
  name: updatecontact-deployment
  labels:
    app: contact-update
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-update
  template:
    metadata:
      labels:
        app: contact-update
    spec:
      containers:
        - name: contact-update
          image: fiap_5nett_tech.api.updatecontact:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5092
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5092"  # Configura para escutar na porta 5092