apiVersion: v1
kind: Service
metadata:
  name: updatecontact-service
spec:
  type: LoadBalancer
  selector:
    app: contact-update
  ports:
    - port: 8085
      targetPort: 5092
      nodePort: 30004