apiVersion: apps/v1
kind: Deployment
metadata:
  name: readcontact-deployment
  labels:
    app: contact-update
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact-update
  template:
    metadata:
      labels:
        app: contact-update
    spec:
      containers:
        - name: contact-update
          image: fiap_5nett_tech.api.updatecontact:latest
          ports:
            - containerPort: 8080