services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "1q2w3e4r@#$"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - mynw

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - mynw

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./infra/grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mynw

  rabbitmq:
    container_name: RabbitMQ
    hostname: rabbitmq
    build:
      context: ./infra/rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672" #management # habilitado visualização no browser
      - "15692:15692" #prometheus # desnecessário
      - "5672:5672" #amqp       # desnecessário
      - "5552:5552" 
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -I -s -L http://localhost:15672 || exit 1"
        ]
      interval: 30s
      timeout: 20s
      retries: 5
    depends_on:
      - grafana
        
    networks:
      - mynw

  fiap_5nett_tech.api.contact.create:
    image: fiap_5nett_tech.api.createcontact
    ports:
      - "5151:5151"
    build:
      context: ./fiap_5nett_tech.Api/fiap_5nett_tech.Api.CreateContact
      dockerfile: Dockerfile
  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5151
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - mynw
  
  fiap_5nett_tech.api.contact.read:
    image: fiap_5nett_tech.api.readcontact
    ports:
      - "5166:5166"
    build:
      context: ./fiap_5nett_tech.Api/fiap_5nett_tech.Api.ReadContact
      dockerfile: Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5166
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - mynw
  
  fiap_5nett_tech.api.contact.update:
    image: fiap_5nett_tech.api.updatecontact
    ports:
      - "5092:5092"
    build:
      context: ./fiap_5nett_tech.Api/fiap_5nett_tech.Api.UpdateContact
      dockerfile: Dockerfile
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5092
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - mynw
  
  fiap_5nett_tech.api.contact.delete:
    image: fiap_5nett_tech.api.deletecontact
    ports:
      - "5149:5149"
    build:
      context: ./fiap_5nett_tech.Api/fiap_5nett_tech.Api.DeleteContact
      dockerfile: Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5149
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - mynw
  
volumes:
  rabbitmq_data:
    
networks:
  mynw: