global:
  scrape_interval: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:

scrape_configs:
  - job_name: 'Api'
    static_configs:
      - targets: ['fiap_5nett_tech_grupo_19-fiap_5nett_tech-1:7015']