apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 15s
      
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
    rule_files:

    scrape_configs:
      - job_name: "prometheus"
        metrics_path: '/metrics'
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "CreateContact"
        metrics_path: '/metrics'
        static_configs:
          - targets: ["createcontact-service.default.svc.cluster.local:8080"]