apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  labels:
    app: sqlserver
spec:
  selector:
    matchLabels:
      app: sqlserver
  replicas: 1
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "1q2w3e4r@#$"
          volumeMounts:
            - name: mssql-storage
              mountPath: /var/opt/mssql   # Caminho onde o SQL Server armazena os dados
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: mssql-pvc   # Nome do PVC que você criou