apiVersion: v1
kind: Service
metadata:
  name: createcontact-service
spec:
  type: LoadBalancer
  selector:
    app: contact-create
  ports:
    - port: 80
      targetPort: 5151
      nodePort: 30001