apiVersion: apps/v1
kind: Deployment
metadata:
  name: createcontact-deployment
  labels:
    app: contact-create
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-create
  template:
    metadata:
      labels:
        app: contact-create
    spec:
      containers:
        - name: contact-create
          image: fiap_5nett_tech.api.createcontact:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5151
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5151"  # Configura para escutar na porta 5151