apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 5672
      nodePort: 30009
      name: amqp
    - port: 8082
      protocol: TCP
      targetPort: 15672
      nodePort: 30007
      name: management
    - port: 8083
      protocol: TCP
      targetPort: 15692
      nodePort: 30010
      name: masstransit