{
 "title": "ASP.NET Core",
 "description": "ASP.NET Core metrics from OpenTelemetry",
 "tags": [
  "dotnet",
  "prometheus",
  "aspnetcore"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(http_requests_received_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_requests_received_total{job=\"$job\"},instance)"
    }
   },
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": {
     "query": "label_values(http_requests_received_total{job=\"$job\", instance=\"$instance\"},endpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", code=~\"4..|5..\"}[$__rate_interval])) or vector(0) / sum(rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", code=~\"4..\"}[$__rate_interval])) or vector(0) / sum(rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", code=~\"5..\"}[$__rate_interval])) or vector(0) / sum(rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(microsoft_aspnetcore_server_kestrel_kestrel_active_connections{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum(microsoft_aspnetcore_hosting_http_server_active_requests{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Unhandled Exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", error_type!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Secured",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(url_scheme) (max_over_time(http_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(max_over_time(http_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval]), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Top 10 Requested Endpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk(10, sum by(endpoint, http_request_method, method) (label_join(max_over_time(http_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval]), \"method_route\", \" \", \"http_request_method\")))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Top 10 Unhandled Exception Endpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum by (endpoint, http_request_method, method_route) (\r\n    label_join(max_over_time(http_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", endpoint!=\"\", error_type!=\"\"}[$__rate_interval]), \"method_route\", \" \", \"http_request_method\", \"endpoint\")\r\n  ))",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}