apiVersion: v1
kind: Service
metadata:
  name: updatecontact-service
spec:
  type: NodePort
  selector:
    app: fiap_5nett_tech.api.contact.update
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30004