apiVersion: apps/v1
kind: Deployment
metadata:
  name: readcontact-deployment
  labels:
    app: contact-read
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-read
  template:
    metadata:
      labels:
        app: contact-read
    spec:
      containers:
        - name: contact-read
          image: fiap_5nett_tech.api.readcontact:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5166
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5166"  # Configura para escutar na porta 5156