apiVersion: apps/v1
kind: Deployment
metadata:
  name: readcontact-deployment
  labels:
    app: contact-read
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact-read
  template:
    metadata:
      labels:
        app: contact-read
    spec:
      containers:
        - name: contact-read
          image: fiap_5nett_tech.api.readcontact:latest
          ports:
            - containerPort: 8080