apiVersion: apps/v1
kind: Deployment
metadata:
  name: deletecontact-deployment
  labels:
    app: contact-delete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-delete
  template:
    metadata:
      labels:
        app: contact-delete
    spec:
      containers:
        - name: contact-delete
          image: fiap_5nett_tech.api.deletecontact:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5149
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5149"  # Configura para escutar na porta 5149