apiVersion: v1
kind: Service
metadata:
  name: deletecontact-service
spec:
  type: LoadBalancer
  selector:
    app: contact-delete
  ports:
    - port: 8086
      targetPort: 5149
      nodePort: 30002