apiVersion: apps/v1
kind: Deployment
metadata:
  name: deletecontact-deployment
  labels:
    app: contact-delete
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact-delete
  template:
    metadata:
      labels:
        app: contact-delete
    spec:
      containers:
        - name: contact-delete
          image: fiap_5nett_tech.api.deletecontact:latest
          ports:
            - containerPort: 8080