apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-config
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        editable: true
        uid: eed6p7966f400c

  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: "Default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards