global:
  scrape_interval: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:

scrape_configs:
  - job_name: 'Api.Contact.Create'
    static_configs:
      - targets: ['localhost:7175']