global:
  scrape_interval: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:

scrape_configs:
  - job_name: 'Api.Contact.Create'
    static_configs:
      - targets: ['fiap_5nett_tech.Api.Contact.Create-1:7175']